#!/bin/sh

MEM="$(grep MemTotal /proc/meminfo | awk '{print $2}')"

while [ true ]
do
	dd if=/dev/zero of=/tmp/dummy count=$((MEM / (1024 * 16))) bs=1M 2>&1 | false
	sleep $[ ( $RANDOM % 4 ) + 1 ]s
done
